# Generated by Django 5.2.3 on 2025-07-13 14:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Fecha')),
                ('total_detections', models.IntegerField(default=0, verbose_name='Total de Detecciones')),
                ('camera_detections', models.IntegerField(default=0, verbose_name='Detecciones por Cámara')),
                ('upload_detections', models.IntegerField(default=0, verbose_name='Detecciones por Subida')),
                ('video_detections', models.IntegerField(default=0, verbose_name='Detecciones por Video')),
                ('unique_plates', models.IntegerField(default=0, verbose_name='Placas Únicas')),
                ('avg_confidence', models.FloatField(default=0.0, verbose_name='Confianza Promedio')),
                ('alerts_triggered', models.IntegerField(default=0, verbose_name='Alertas Activadas')),
            ],
            options={
                'verbose_name': 'Estadística de Detección',
                'verbose_name_plural': 'Estadísticas de Detecciones',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='VehicleAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=20, unique=True, verbose_name='Número de Placa')),
                ('alert_type', models.CharField(choices=[('blacklist', 'Lista Negra'), ('whitelist', 'Lista Blanca'), ('stolen', 'Reportado como Robado'), ('expired', 'Documentos Vencidos'), ('custom', 'Personalizado')], max_length=20, verbose_name='Tipo de Alerta')),
                ('description', models.TextField(help_text='Descripción de la alerta', verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Expiración')),
            ],
            options={
                'verbose_name': 'Alerta de Vehículo',
                'verbose_name_plural': 'Alertas de Vehículos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlateDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(help_text='Número de placa detectado', max_length=20, verbose_name='Número de Placa')),
                ('confidence', models.FloatField(help_text='Nivel de confianza de la detección (0.0 - 1.0)', verbose_name='Confianza')),
                ('detection_method', models.CharField(choices=[('Google Vision', 'Google Vision API'), ('EasyOCR', 'EasyOCR'), ('EasyOCR Pro', 'EasyOCR Procesada'), ('Ninguno', 'No Detectado')], default='EasyOCR', max_length=20, verbose_name='Método de Detección')),
                ('detection_type', models.CharField(choices=[('manual', 'Subida Manual'), ('camera', 'Cámara Web'), ('upload', 'Archivo Subido'), ('video', 'Video'), ('realtime', 'Tiempo Real')], default='manual', max_length=20, verbose_name='Tipo de Detección')),
                ('image_path', models.CharField(blank=True, help_text='Ruta del archivo de imagen procesado', max_length=500, null=True, verbose_name='Ruta de Imagen')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Detección')),
                ('notes', models.TextField(blank=True, help_text='Notas adicionales sobre la detección', verbose_name='Notas')),
                ('is_verified', models.BooleanField(default=False, help_text='Indica si la detección ha sido verificada manualmente', verbose_name='Verificado')),
            ],
            options={
                'verbose_name': 'Detección de Placa',
                'verbose_name_plural': 'Detecciones de Placas',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['plate_number'], name='deteccion_p_plate_n_cd792f_idx'), models.Index(fields=['created_at'], name='deteccion_p_created_9972dd_idx'), models.Index(fields=['detection_type'], name='deteccion_p_detecti_a1329c_idx')],
            },
        ),
    ]
